oracle:
  username: username
  password: password

# via_options must use symbols for keys cuz Pony wants it that way
email:
  from:    'noreply@example.com'
  subject: 'Barcode Recovery'
  via:     :smtp
  via_options:
    :address:   'smtp.gmail.com'
    :port:      '587'
    :enable_starttls_auto: true
    :user_name: 'user@gmail.com'
    :password:  'password'
    :authentication: :plain
    :domain:    'localhost.localdomain'

  
